"""modify role

Revision ID: 10825e3d7d25
Revises: 2f7655868627
Create Date: 2018-09-11 20:37:27.165090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10825e3d7d25'
down_revision = '2f7655868627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
