"""add email to users

Revision ID: 209d29e75f2c
Revises: f6f7f2fe4625
Create Date: 2018-08-21 10:04:26.068190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209d29e75f2c'
down_revision = 'f6f7f2fe4625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
